# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        mainWindow.setMinimumSize(QtCore.QSize(800, 600))
        mainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        mainWindow.setFont(font)
        mainWindow.setIconSize(QtCore.QSize(48, 48))
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setSizeIncrement(QtCore.QSize(1, 1))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(11, 3, 781, 491))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetHeaderBox = QtWidgets.QHBoxLayout()
        self.widgetHeaderBox.setObjectName("widgetHeaderBox")
        self.widgetAddCustomer = QtWidgets.QVBoxLayout()
        self.widgetAddCustomer.setObjectName("widgetAddCustomer")
        self.widgetTextBoxes = QtWidgets.QVBoxLayout()
        self.widgetTextBoxes.setObjectName("widgetTextBoxes")
        self.widgetNamePhone = QtWidgets.QGridLayout()
        self.widgetNamePhone.setObjectName("widgetNamePhone")
        self.txtNewCompany = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtNewCompany.setFont(font)
        self.txtNewCompany.setObjectName("txtNewCompany")
        self.widgetNamePhone.addWidget(self.txtNewCompany, 0, 0, 1, 1)
        self.txtNewPhone1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtNewPhone1.setFont(font)
        self.txtNewPhone1.setObjectName("txtNewPhone1")
        self.widgetNamePhone.addWidget(self.txtNewPhone1, 0, 1, 1, 1)
        self.widgetTextBoxes.addLayout(self.widgetNamePhone)
        self.widgetAddCustomer.addLayout(self.widgetTextBoxes)
        self.widgetAddButton = QtWidgets.QVBoxLayout()
        self.widgetAddButton.setObjectName("widgetAddButton")
        self.btnAddCustomer = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAddCustomer.setFont(font)
        self.btnAddCustomer.setObjectName("btnAddCustomer")
        self.widgetAddButton.addWidget(self.btnAddCustomer)
        self.widgetAddCustomer.addLayout(self.widgetAddButton)
        self.widgetHeaderBox.addLayout(self.widgetAddCustomer)
        self.widgetWorkdate = QtWidgets.QGridLayout()
        self.widgetWorkdate.setObjectName("widgetWorkdate")
        self.btnCreateReportDialog = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCreateReportDialog.setFont(font)
        self.btnCreateReportDialog.setObjectName("btnCreateReportDialog")
        self.widgetWorkdate.addWidget(self.btnCreateReportDialog, 2, 0, 1, 1)
        self.txtWorkdate = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtWorkdate.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txtWorkdate.setFont(font)
        self.txtWorkdate.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWorkdate.setReadOnly(False)
        self.txtWorkdate.setObjectName("txtWorkdate")
        self.widgetWorkdate.addWidget(self.txtWorkdate, 1, 0, 1, 1)
        self.widgetHeaderBox.addLayout(self.widgetWorkdate)
        self.widgetLastUpdate = QtWidgets.QGridLayout()
        self.widgetLastUpdate.setObjectName("widgetLastUpdate")
        self.txtCustServer = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtCustServer.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtCustServer.setFont(font)
        self.txtCustServer.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCustServer.setReadOnly(True)
        self.txtCustServer.setObjectName("txtCustServer")
        self.widgetLastUpdate.addWidget(self.txtCustServer, 0, 2, 1, 1)
        self.lblCustomer = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblCustomer.setFont(font)
        self.lblCustomer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblCustomer.setObjectName("lblCustomer")
        self.widgetLastUpdate.addWidget(self.lblCustomer, 0, 0, 1, 1)
        self.lblCatalog = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblCatalog.setFont(font)
        self.lblCatalog.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblCatalog.setObjectName("lblCatalog")
        self.widgetLastUpdate.addWidget(self.lblCatalog, 1, 0, 1, 1)
        self.txtCustLocal = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtCustLocal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtCustLocal.setFont(font)
        self.txtCustLocal.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCustLocal.setReadOnly(True)
        self.txtCustLocal.setObjectName("txtCustLocal")
        self.widgetLastUpdate.addWidget(self.txtCustLocal, 0, 1, 1, 1)
        self.txtProdServer = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtProdServer.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtProdServer.setFont(font)
        self.txtProdServer.setAlignment(QtCore.Qt.AlignCenter)
        self.txtProdServer.setReadOnly(True)
        self.txtProdServer.setObjectName("txtProdServer")
        self.widgetLastUpdate.addWidget(self.txtProdServer, 1, 2, 1, 1)
        self.txtProdLocal = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtProdLocal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtProdLocal.setFont(font)
        self.txtProdLocal.setAlignment(QtCore.Qt.AlignCenter)
        self.txtProdLocal.setReadOnly(True)
        self.txtProdLocal.setObjectName("txtProdLocal")
        self.widgetLastUpdate.addWidget(self.txtProdLocal, 1, 1, 1, 1)
        self.widgetHeaderBox.addLayout(self.widgetLastUpdate)
        self.verticalLayout.addLayout(self.widgetHeaderBox)
        self.mainGrid = QtWidgets.QHBoxLayout()
        self.mainGrid.setObjectName("mainGrid")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widgetCustomerInfo = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widgetCustomerInfo.setFont(font)
        self.widgetCustomerInfo.setObjectName("widgetCustomerInfo")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widgetCustomerList = QtWidgets.QTreeWidget(self.tab)
        self.widgetCustomerList.setGeometry(QtCore.QRect(10, 10, 751, 350))
        self.widgetCustomerList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetCustomerList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetCustomerList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.widgetCustomerList.setAlternatingRowColors(True)
        self.widgetCustomerList.setIndentation(20)
        self.widgetCustomerList.setRootIsDecorated(False)
        self.widgetCustomerList.setItemsExpandable(False)
        self.widgetCustomerList.setExpandsOnDoubleClick(False)
        self.widgetCustomerList.setColumnCount(2)
        self.widgetCustomerList.setObjectName("widgetCustomerList")
        self.widgetCustomerList.header().setDefaultSectionSize(80)
        self.widgetCustomerInfo.addTab(self.tab, "")
        self.widgetCustomerInfoPage1 = QtWidgets.QWidget()
        self.widgetCustomerInfoPage1.setObjectName("widgetCustomerInfoPage1")
        self.layoutWidget = QtWidgets.QWidget(self.widgetCustomerInfoPage1)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 340, 180))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.widgetMasterDetails = QtWidgets.QGridLayout(self.layoutWidget)
        self.widgetMasterDetails.setContentsMargins(0, 0, 0, 0)
        self.widgetMasterDetails.setObjectName("widgetMasterDetails")
        self.txtPhone2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtPhone2.setFont(font)
        self.txtPhone2.setObjectName("txtPhone2")
        self.widgetMasterDetails.addWidget(self.txtPhone2, 2, 1, 1, 1)
        self.txtPhone1 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtPhone1.setFont(font)
        self.txtPhone1.setObjectName("txtPhone1")
        self.widgetMasterDetails.addWidget(self.txtPhone1, 1, 1, 1, 1)
        self.txtFactor = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtFactor.setFont(font)
        self.txtFactor.setObjectName("txtFactor")
        self.widgetMasterDetails.addWidget(self.txtFactor, 4, 1, 1, 1)
        self.txtAccount = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtAccount.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtAccount.setFont(font)
        self.txtAccount.setReadOnly(True)
        self.txtAccount.setObjectName("txtAccount")
        self.widgetMasterDetails.addWidget(self.txtAccount, 0, 1, 1, 1)
        self.txtCompany = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtCompany.setFont(font)
        self.txtCompany.setObjectName("txtCompany")
        self.widgetMasterDetails.addWidget(self.txtCompany, 0, 0, 1, 1)
        self.txtAddress1 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtAddress1.setFont(font)
        self.txtAddress1.setObjectName("txtAddress1")
        self.widgetMasterDetails.addWidget(self.txtAddress1, 1, 0, 1, 1)
        self.txtAddress2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtAddress2.setFont(font)
        self.txtAddress2.setObjectName("txtAddress2")
        self.widgetMasterDetails.addWidget(self.txtAddress2, 2, 0, 1, 1)
        self.txtZipCode = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtZipCode.setFont(font)
        self.txtZipCode.setObjectName("txtZipCode")
        self.widgetMasterDetails.addWidget(self.txtZipCode, 3, 0, 1, 1)
        self.txtCityName = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtCityName.setFont(font)
        self.txtCityName.setObjectName("txtCityName")
        self.widgetMasterDetails.addWidget(self.txtCityName, 4, 0, 1, 1)
        self.txtEmail = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txtEmail.setFont(font)
        self.txtEmail.setObjectName("txtEmail")
        self.widgetMasterDetails.addWidget(self.txtEmail, 3, 1, 1, 1)
        self.txtCustomerInfoText = QtWidgets.QTextEdit(self.widgetCustomerInfoPage1)
        self.txtCustomerInfoText.setGeometry(QtCore.QRect(10, 200, 340, 80))
        self.txtCustomerInfoText.setObjectName("txtCustomerInfoText")
        self.btnArchiveContacts = QtWidgets.QPushButton(self.widgetCustomerInfoPage1)
        self.btnArchiveContacts.setGeometry(QtCore.QRect(620, 290, 142, 27))
        self.btnArchiveContacts.setObjectName("btnArchiveContacts")
        self.btnAddContact = QtWidgets.QPushButton(self.widgetCustomerInfoPage1)
        self.btnAddContact.setGeometry(QtCore.QRect(470, 290, 140, 27))
        self.btnAddContact.setObjectName("btnAddContact")
        self.widgetContactList = QtWidgets.QTreeWidget(self.widgetCustomerInfoPage1)
        self.widgetContactList.setGeometry(QtCore.QRect(360, 10, 410, 270))
        self.widgetContactList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetContactList.setIndentation(0)
        self.widgetContactList.setRootIsDecorated(False)
        self.widgetContactList.setItemsExpandable(False)
        self.widgetContactList.setExpandsOnDoubleClick(False)
        self.widgetContactList.setObjectName("widgetContactList")
        self.btnArchiveMasterdata = QtWidgets.QPushButton(self.widgetCustomerInfoPage1)
        self.btnArchiveMasterdata.setGeometry(QtCore.QRect(210, 290, 142, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnArchiveMasterdata.setFont(font)
        self.btnArchiveMasterdata.setObjectName("btnArchiveMasterdata")
        self.widgetCustomerInfo.addTab(self.widgetCustomerInfoPage1, "")
        self.widgetCustomerInfoPage3 = QtWidgets.QWidget()
        self.widgetCustomerInfoPage3.setObjectName("widgetCustomerInfoPage3")
        self.widgetVisitDetails = QtWidgets.QTreeWidget(self.widgetCustomerInfoPage3)
        self.widgetVisitDetails.setGeometry(QtCore.QRect(320, 260, 450, 110))
        self.widgetVisitDetails.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetVisitDetails.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.widgetVisitDetails.setAlternatingRowColors(True)
        self.widgetVisitDetails.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.widgetVisitDetails.setIndentation(0)
        self.widgetVisitDetails.setRootIsDecorated(False)
        self.widgetVisitDetails.setItemsExpandable(False)
        self.widgetVisitDetails.setObjectName("widgetVisitDetails")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widgetCustomerInfoPage3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 270, 450, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.txtSale = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSale.sizePolicy().hasHeightForWidth())
        self.txtSale.setSizePolicy(sizePolicy)
        self.txtSale.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txtSale.setReadOnly(True)
        self.txtSale.setObjectName("txtSale")
        self.gridLayout_4.addWidget(self.txtSale, 0, 3, 1, 1)
        self.txtPoNumber = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPoNumber.sizePolicy().hasHeightForWidth())
        self.txtPoNumber.setSizePolicy(sizePolicy)
        self.txtPoNumber.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txtPoNumber.setReadOnly(True)
        self.txtPoNumber.setObjectName("txtPoNumber")
        self.gridLayout_4.addWidget(self.txtPoNumber, 0, 1, 1, 1)
        self.lblSent = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSent.sizePolicy().hasHeightForWidth())
        self.lblSent.setSizePolicy(sizePolicy)
        self.lblSent.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSent.setFont(font)
        self.lblSent.setText("")
        self.lblSent.setObjectName("lblSent")
        self.gridLayout_4.addWidget(self.lblSent, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.lblApproved = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblApproved.sizePolicy().hasHeightForWidth())
        self.lblApproved.setSizePolicy(sizePolicy)
        self.lblApproved.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblApproved.setFont(font)
        self.lblApproved.setText("")
        self.lblApproved.setObjectName("lblApproved")
        self.gridLayout_4.addWidget(self.lblApproved, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 2, 1, 1)
        self.txtSas = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSas.sizePolicy().hasHeightForWidth())
        self.txtSas.setSizePolicy(sizePolicy)
        self.txtSas.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txtSas.setReadOnly(True)
        self.txtSas.setObjectName("txtSas")
        self.gridLayout_4.addWidget(self.txtSas, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 2, 1, 1)
        self.txtTotal = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtTotal.sizePolicy().hasHeightForWidth())
        self.txtTotal.setSizePolicy(sizePolicy)
        self.txtTotal.setMaximumSize(QtCore.QSize(16777215, 20))
        self.txtTotal.setReadOnly(True)
        self.txtTotal.setObjectName("txtTotal")
        self.gridLayout_4.addWidget(self.txtTotal, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.txtVisitInfoText = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.txtVisitInfoText.setReadOnly(True)
        self.txtVisitInfoText.setObjectName("txtVisitInfoText")
        self.horizontalLayout.addWidget(self.txtVisitInfoText)
        self.btnVisitDialog = QtWidgets.QPushButton(self.widgetCustomerInfoPage3)
        self.btnVisitDialog.setGeometry(QtCore.QRect(540, 10, 142, 27))
        self.btnVisitDialog.setObjectName("btnVisitDialog")
        self.tabWidget = QtWidgets.QTabWidget(self.widgetCustomerInfoPage3)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 511, 201))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widgetVisitList = QtWidgets.QTreeWidget(self.tab_3)
        self.widgetVisitList.setGeometry(QtCore.QRect(0, 10, 480, 120))
        self.widgetVisitList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.widgetVisitList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.widgetVisitList.setAlternatingRowColors(True)
        self.widgetVisitList.setIndentation(0)
        self.widgetVisitList.setRootIsDecorated(False)
        self.widgetVisitList.setItemsExpandable(False)
        self.widgetVisitList.setExpandsOnDoubleClick(False)
        self.widgetVisitList.setObjectName("widgetVisitList")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.widgetCustomerInfo.addTab(self.widgetCustomerInfoPage3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widgetCustomerInfo.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.widgetCustomerInfo)
        self.mainGrid.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.mainGrid)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menuCustomer = QtWidgets.QMenu(self.menuData)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/system/companies.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuCustomer.setIcon(icon)
        self.menuCustomer.setObjectName("menuCustomer")
        self.menuServer = QtWidgets.QMenu(self.menuData)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/system/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuServer.setIcon(icon1)
        self.menuServer.setObjectName("menuServer")
        self.menuReports = QtWidgets.QMenu(self.menuData)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/system/reports.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuReports.setIcon(icon2)
        self.menuReports.setObjectName("menuReports")
        self.menuImport = QtWidgets.QMenu(self.menuData)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/system/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuImport.setIcon(icon3)
        self.menuImport.setObjectName("menuImport")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(self.menuHelp)
        self.menuAbout.setObjectName("menuAbout")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toolBar.setFont(font)
        self.toolBar.setLocale(QtCore.QLocale(QtCore.QLocale.Danish, QtCore.QLocale.Denmark))
        self.toolBar.setMovable(True)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(mainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/system/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(mainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/system/config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon5)
        self.actionSettings.setObjectName("actionSettings")
        self.actionGetCustomersHttp = QtWidgets.QAction(mainWindow)
        self.actionGetCustomersHttp.setObjectName("actionGetCustomersHttp")
        self.actionGetCatalogHttp = QtWidgets.QAction(mainWindow)
        self.actionGetCatalogHttp.setObjectName("actionGetCatalogHttp")
        self.actionAboutQt = QtWidgets.QAction(mainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionAboutSoftware = QtWidgets.QAction(mainWindow)
        self.actionAboutSoftware.setObjectName("actionAboutSoftware")
        self.actionImportCsvFiles = QtWidgets.QAction(mainWindow)
        self.actionImportCsvFiles.setObjectName("actionImportCsvFiles")
        self.actionMasterInfo = QtWidgets.QAction(mainWindow)
        self.actionMasterInfo.setObjectName("actionMasterInfo")
        self.actionContactsInfo = QtWidgets.QAction(mainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/system/contacts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionContactsInfo.setIcon(icon6)
        self.actionContactsInfo.setObjectName("actionContactsInfo")
        self.actionVisitsInfo = QtWidgets.QAction(mainWindow)
        self.actionVisitsInfo.setObjectName("actionVisitsInfo")
        self.actionVisitDetails = QtWidgets.QAction(mainWindow)
        self.actionVisitDetails.setObjectName("actionVisitDetails")
        self.actionCreateVisit = QtWidgets.QAction(mainWindow)
        self.actionCreateVisit.setObjectName("actionCreateVisit")
        self.actionCreateCustomer = QtWidgets.QAction(mainWindow)
        self.actionCreateCustomer.setObjectName("actionCreateCustomer")
        self.actionArchiveChanges = QtWidgets.QAction(mainWindow)
        self.actionArchiveChanges.setObjectName("actionArchiveChanges")
        self.actionReport = QtWidgets.QAction(mainWindow)
        self.actionReport.setObjectName("actionReport")
        self.actionZeroDatabase = QtWidgets.QAction(mainWindow)
        self.actionZeroDatabase.setObjectName("actionZeroDatabase")
        self.actionReportList = QtWidgets.QAction(mainWindow)
        self.actionReportList.setObjectName("actionReportList")
        self.menuExit.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionSettings)
        self.menuSettings.addSeparator()
        self.menuCustomer.addAction(self.actionMasterInfo)
        self.menuCustomer.addAction(self.actionContactsInfo)
        self.menuCustomer.addAction(self.actionVisitsInfo)
        self.menuCustomer.addSeparator()
        self.menuCustomer.addAction(self.actionArchiveChanges)
        self.menuServer.addAction(self.actionGetCatalogHttp)
        self.menuServer.addAction(self.actionGetCustomersHttp)
        self.menuReports.addAction(self.actionReport)
        self.menuReports.addAction(self.actionReportList)
        self.menuImport.addAction(self.actionImportCsvFiles)
        self.menuImport.addSeparator()
        self.menuImport.addAction(self.actionZeroDatabase)
        self.menuData.addAction(self.actionCreateCustomer)
        self.menuData.addAction(self.menuCustomer.menuAction())
        self.menuData.addAction(self.menuReports.menuAction())
        self.menuData.addAction(self.menuServer.menuAction())
        self.menuData.addAction(self.menuImport.menuAction())
        self.menuAbout.addAction(self.actionAboutQt)
        self.menuAbout.addAction(self.actionAboutSoftware)
        self.menuHelp.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(mainWindow)
        self.widgetCustomerInfo.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.txtNewCompany, self.txtNewPhone1)
        mainWindow.setTabOrder(self.txtNewPhone1, self.txtWorkdate)
        mainWindow.setTabOrder(self.txtWorkdate, self.txtCustLocal)
        mainWindow.setTabOrder(self.txtCustLocal, self.txtCustServer)
        mainWindow.setTabOrder(self.txtCustServer, self.txtProdLocal)
        mainWindow.setTabOrder(self.txtProdLocal, self.txtProdServer)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Eordre"))
        self.txtNewCompany.setToolTip(_translate("mainWindow", "navn for ny kunde"))
        self.txtNewCompany.setStatusTip(_translate("mainWindow", "Her indsættes firmanavn for kunde der skal oprettes"))
        self.txtNewCompany.setPlaceholderText(_translate("mainWindow", "navn"))
        self.txtNewPhone1.setToolTip(_translate("mainWindow", "telefon for ny kunde"))
        self.txtNewPhone1.setStatusTip(_translate("mainWindow", "Her indsættes telefon nummer for kunde der skal oprettes\n"
"                                                "))
        self.txtNewPhone1.setPlaceholderText(_translate("mainWindow", "telefon"))
        self.btnAddCustomer.setToolTip(_translate("mainWindow", "Opret ny kunde"))
        self.btnAddCustomer.setStatusTip(_translate("mainWindow", "Udfyld felterne og tryk her for at oprette firma"))
        self.btnAddCustomer.setText(_translate("mainWindow", "Opret kunde"))
        self.btnCreateReportDialog.setToolTip(_translate("mainWindow", "Opret dagsrapport"))
        self.btnCreateReportDialog.setStatusTip(_translate("mainWindow", "Her opretter du en dagsrapport datoen i feltet"))
        self.btnCreateReportDialog.setText(_translate("mainWindow", "Opret dagsrapport"))
        self.txtWorkdate.setToolTip(_translate("mainWindow", "Arbejdsdato"))
        self.txtWorkdate.setStatusTip(_translate("mainWindow", "Dette er systemets arbejdsdato"))
        self.txtWorkdate.setPlaceholderText(_translate("mainWindow", "arbejdsdato"))
        self.txtCustServer.setToolTip(_translate("mainWindow", "Tilgængelig kundeliste"))
        self.txtCustServer.setStatusTip(_translate("mainWindow", "Dette datoen for serverens kundeliste"))
        self.txtCustServer.setPlaceholderText(_translate("mainWindow", "dato"))
        self.lblCustomer.setText(_translate("mainWindow", "Kundeliste"))
        self.lblCatalog.setText(_translate("mainWindow", "Prisliste"))
        self.txtCustLocal.setToolTip(_translate("mainWindow", "Kundeliste synkroniseret"))
        self.txtCustLocal.setStatusTip(_translate("mainWindow", "Dette er dato for sidste synkronisering af kundeliste"))
        self.txtCustLocal.setPlaceholderText(_translate("mainWindow", "dato"))
        self.txtProdServer.setToolTip(_translate("mainWindow", "Tilgængelig prisliste"))
        self.txtProdServer.setStatusTip(_translate("mainWindow", "Dette er datoen for serverens prisliste"))
        self.txtProdServer.setPlaceholderText(_translate("mainWindow", "dato"))
        self.txtProdLocal.setToolTip(_translate("mainWindow", "Prisliste synkroniseret"))
        self.txtProdLocal.setStatusTip(_translate("mainWindow", "Dette er dato for sidste synkronisering af prisliste"))
        self.txtProdLocal.setPlaceholderText(_translate("mainWindow", "dato"))
        self.widgetCustomerList.headerItem().setText(0, _translate("mainWindow", "Telefon"))
        self.widgetCustomerList.headerItem().setText(1, _translate("mainWindow", "Firmanavn"))
        self.widgetCustomerInfo.setTabText(self.widgetCustomerInfo.indexOf(self.tab), _translate("mainWindow", "Kundeliste"))
        self.txtPhone2.setToolTip(_translate("mainWindow", "Anden telefon"))
        self.txtPhone2.setStatusTip(_translate("mainWindow", "Dette felt er mobil eller anden telefon til\n"
"                                                                        kunde\n"
"                                                                    "))
        self.txtPhone2.setPlaceholderText(_translate("mainWindow", "mobil telefon"))
        self.txtPhone1.setToolTip(_translate("mainWindow", "Primær telefon"))
        self.txtPhone1.setStatusTip(_translate("mainWindow", "Dette felt er primær telefon til kunde\n"
"                                                                    "))
        self.txtPhone1.setPlaceholderText(_translate("mainWindow", "primær telefon"))
        self.txtFactor.setToolTip(_translate("mainWindow", "Faktor"))
        self.txtFactor.setStatusTip(_translate("mainWindow", "Ved salg bliver liste priser ganget med\n"
"                                                                        faktor\n"
"                                                                    "))
        self.txtFactor.setPlaceholderText(_translate("mainWindow", "faktor"))
        self.txtAccount.setToolTip(_translate("mainWindow", "Kundekonto"))
        self.txtAccount.setStatusTip(_translate("mainWindow", "Dette felt er konto for kunde"))
        self.txtAccount.setPlaceholderText(_translate("mainWindow", "konto"))
        self.txtCompany.setToolTip(_translate("mainWindow", "Firmanavn"))
        self.txtCompany.setStatusTip(_translate("mainWindow", "Dette felt er kunde navn"))
        self.txtCompany.setPlaceholderText(_translate("mainWindow", "firma navn"))
        self.txtAddress1.setToolTip(_translate("mainWindow", "Kundens adresse"))
        self.txtAddress1.setStatusTip(_translate("mainWindow", "Dette felt er kunde adresse"))
        self.txtAddress1.setPlaceholderText(_translate("mainWindow", "adresse"))
        self.txtAddress2.setToolTip(_translate("mainWindow", "Udvidet adresse"))
        self.txtAddress2.setStatusTip(_translate("mainWindow", "Dette felt er udvidet adresse"))
        self.txtAddress2.setPlaceholderText(_translate("mainWindow", "adresse"))
        self.txtZipCode.setToolTip(_translate("mainWindow", "Postnummer"))
        self.txtZipCode.setStatusTip(_translate("mainWindow", "Dette felt er postnummer for kunde"))
        self.txtZipCode.setPlaceholderText(_translate("mainWindow", "post nummer"))
        self.txtCityName.setToolTip(_translate("mainWindow", "Bynavn"))
        self.txtCityName.setStatusTip(_translate("mainWindow", "Dette felt er bynavn for kunde"))
        self.txtCityName.setPlaceholderText(_translate("mainWindow", "by navn"))
        self.txtEmail.setToolTip(_translate("mainWindow", "Epost adresse"))
        self.txtEmail.setStatusTip(_translate("mainWindow", "Dette felt er epost adresse for kunde\n"
"                                                                    "))
        self.txtEmail.setPlaceholderText(_translate("mainWindow", "epost adresse"))
        self.btnArchiveContacts.setText(_translate("mainWindow", "Arkiver kontakter"))
        self.btnAddContact.setText(_translate("mainWindow", "Tilføj kontakt ..."))
        self.widgetContactList.headerItem().setText(0, _translate("mainWindow", "Navn"))
        self.widgetContactList.headerItem().setText(1, _translate("mainWindow", "Telefon"))
        self.widgetContactList.headerItem().setText(2, _translate("mainWindow", "Afdeling"))
        self.widgetContactList.headerItem().setText(3, _translate("mainWindow", "Email"))
        self.widgetContactList.headerItem().setText(4, _translate("mainWindow", "Info"))
        self.btnArchiveMasterdata.setToolTip(_translate("mainWindow", "Arkiver ændringer"))
        self.btnArchiveMasterdata.setStatusTip(_translate("mainWindow", "Tryk her for at gemme rettelser i\n"
"                                                                        databasen\n"
"                                                                    "))
        self.btnArchiveMasterdata.setText(_translate("mainWindow", "Arkiver kunde"))
        self.widgetCustomerInfo.setTabText(self.widgetCustomerInfo.indexOf(self.widgetCustomerInfoPage1), _translate("mainWindow", "Stamdata"))
        self.widgetVisitDetails.headerItem().setText(0, _translate("mainWindow", "*"))
        self.widgetVisitDetails.headerItem().setText(1, _translate("mainWindow", "Ant"))
        self.widgetVisitDetails.headerItem().setText(2, _translate("mainWindow", "SKU"))
        self.widgetVisitDetails.headerItem().setText(3, _translate("mainWindow", "Vare"))
        self.widgetVisitDetails.headerItem().setText(4, _translate("mainWindow", "Pris"))
        self.widgetVisitDetails.headerItem().setText(5, _translate("mainWindow", "%"))
        self.widgetVisitDetails.headerItem().setText(6, _translate("mainWindow", "Ekstra"))
        self.label_4.setText(_translate("mainWindow", "Salg"))
        self.label_3.setText(_translate("mainWindow", "Rekv."))
        self.label_7.setText(_translate("mainWindow", "Afsl."))
        self.label_6.setText(_translate("mainWindow", "SAS"))
        self.label_5.setText(_translate("mainWindow", "Total"))
        self.label_8.setText(_translate("mainWindow", "Godk."))
        self.btnVisitDialog.setText(_translate("mainWindow", "Tilføj besøg ..."))
        self.widgetVisitList.headerItem().setText(0, _translate("mainWindow", "Id"))
        self.widgetVisitList.headerItem().setText(1, _translate("mainWindow", "Dato"))
        self.widgetVisitList.headerItem().setText(2, _translate("mainWindow", "Navn"))
        self.widgetVisitList.headerItem().setText(3, _translate("mainWindow", "Demo"))
        self.widgetVisitList.headerItem().setText(4, _translate("mainWindow", "Salg"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("mainWindow", "Tab 2"))
        self.widgetCustomerInfo.setTabText(self.widgetCustomerInfo.indexOf(self.widgetCustomerInfoPage3), _translate("mainWindow", "Besøg"))
        self.widgetCustomerInfo.setTabText(self.widgetCustomerInfo.indexOf(self.tab_2), _translate("mainWindow", "Prisliste"))
        self.menuExit.setTitle(_translate("mainWindow", "Afslut"))
        self.menuSettings.setTitle(_translate("mainWindow", "Indstillinger"))
        self.menuData.setTitle(_translate("mainWindow", "Data"))
        self.menuCustomer.setTitle(_translate("mainWindow", "Kunde"))
        self.menuServer.setTitle(_translate("mainWindow", "Server"))
        self.menuReports.setTitle(_translate("mainWindow", "Rapporter"))
        self.menuImport.setTitle(_translate("mainWindow", "Import CSV"))
        self.menuHelp.setTitle(_translate("mainWindow", "Hjælp"))
        self.menuAbout.setTitle(_translate("mainWindow", "Om"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.actionExit.setText(_translate("mainWindow", "Afslut"))
        self.actionExit.setIconText(_translate("mainWindow", "Afslut"))
        self.actionExit.setToolTip(_translate("mainWindow", "Afslutter programmet"))
        self.actionExit.setStatusTip(_translate("mainWindow", "Du afslutter programmet ved at trykke her"))
        self.actionExit.setShortcut(_translate("mainWindow", "Ctrl+Q"))
        self.actionSettings.setText(_translate("mainWindow", "Indstillinger"))
        self.actionSettings.setToolTip(_translate("mainWindow", "Tilpas indstillinger"))
        self.actionSettings.setStatusTip(_translate("mainWindow", "Her tilpasser du app\'ens indstillinger"))
        self.actionSettings.setShortcut(_translate("mainWindow", "Ctrl+S"))
        self.actionGetCustomersHttp.setText(_translate("mainWindow", "Hent kunder"))
        self.actionGetCustomersHttp.setStatusTip(_translate("mainWindow", "Her hentes kunder fra server"))
        self.actionGetCatalogHttp.setText(_translate("mainWindow", "Hent Prisliste"))
        self.actionGetCatalogHttp.setStatusTip(_translate("mainWindow", "Her hentes prisliste fra server"))
        self.actionAboutQt.setText(_translate("mainWindow", "Om Qt"))
        self.actionAboutQt.setStatusTip(_translate("mainWindow", "Oplysning om Qt version"))
        self.actionAboutSoftware.setText(_translate("mainWindow", "Om programmet"))
        self.actionAboutSoftware.setStatusTip(_translate("mainWindow", "Oplysning om program version"))
        self.actionImportCsvFiles.setText(_translate("mainWindow", "Fil import"))
        self.actionMasterInfo.setText(_translate("mainWindow", "Stamdata"))
        self.actionContactsInfo.setText(_translate("mainWindow", "Kontakter"))
        self.actionVisitsInfo.setText(_translate("mainWindow", "Historik"))
        self.actionVisitDetails.setText(_translate("mainWindow", "Ordrer"))
        self.actionCreateVisit.setText(_translate("mainWindow", "Opret ordre"))
        self.actionCreateCustomer.setText(_translate("mainWindow", "Opret kunde"))
        self.actionArchiveChanges.setText(_translate("mainWindow", "Arkiver rettelser"))
        self.actionReport.setText(_translate("mainWindow", "Dagsrapport"))
        self.actionZeroDatabase.setText(_translate("mainWindow", "Nulstil database"))
        self.actionReportList.setText(_translate("mainWindow", "Rapport oversigt"))

from . import system_rc
