# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    """
    """
    def setupUi(self, MainWindow):
        """

        Args:
            MainWindow:
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 770)
        MainWindow.setMinimumSize(QtCore.QSize(800, 700))
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setIconSize(QtCore.QSize(48, 48))
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setSizeIncrement(QtCore.QSize(1, 1))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topGridLayout = QtWidgets.QHBoxLayout()
        self.topGridLayout.setObjectName("topGridLayout")
        self.newCustomerGrid = QtWidgets.QGridLayout()
        self.newCustomerGrid.setObjectName("newCustomerGrid")
        self.txtNewPhone1 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtNewPhone1.setObjectName("txtNewPhone1")
        self.newCustomerGrid.addWidget(self.txtNewPhone1, 1, 1, 1, 1)
        self.txtNewCompany = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtNewCompany.setObjectName("txtNewCompany")
        self.newCustomerGrid.addWidget(self.txtNewCompany, 1, 0, 1, 1)
        self.buttonCreateCustomer = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonCreateCustomer.setObjectName("buttonCreateCustomer")
        self.newCustomerGrid.addWidget(self.buttonCreateCustomer, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.newCustomerGrid.addWidget(self.label, 0, 0, 1, 1)
        self.topGridLayout.addLayout(self.newCustomerGrid)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.topGridLayout.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelWorkdate = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelWorkdate.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.labelWorkdate.setObjectName("labelWorkdate")
        self.gridLayout.addWidget(self.labelWorkdate, 0, 0, 1, 1)
        self.txtWorkdate = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtWorkdate.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtWorkdate.setFont(font)
        self.txtWorkdate.setAlignment(QtCore.Qt.AlignCenter)
        self.txtWorkdate.setReadOnly(True)
        self.txtWorkdate.setObjectName("txtWorkdate")
        self.gridLayout.addWidget(self.txtWorkdate, 2, 0, 1, 1)
        self.buttonReport = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonReport.setObjectName("buttonReport")
        self.gridLayout.addWidget(self.buttonReport, 3, 0, 1, 1)
        self.topGridLayout.addLayout(self.gridLayout)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.topGridLayout.addWidget(self.line_2)
        self.lastUpdateGrid = QtWidgets.QGridLayout()
        self.lastUpdateGrid.setObjectName("lastUpdateGrid")
        self.lblAvailable = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblAvailable.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAvailable.setObjectName("lblAvailable")
        self.lastUpdateGrid.addWidget(self.lblAvailable, 0, 2, 1, 1)
        self.txtProdServer = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtProdServer.setEnabled(True)
        self.txtProdServer.setAlignment(QtCore.Qt.AlignCenter)
        self.txtProdServer.setReadOnly(True)
        self.txtProdServer.setObjectName("txtProdServer")
        self.lastUpdateGrid.addWidget(self.txtProdServer, 2, 2, 1, 1)
        self.txtProdLocal = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtProdLocal.setEnabled(True)
        self.txtProdLocal.setAlignment(QtCore.Qt.AlignCenter)
        self.txtProdLocal.setReadOnly(True)
        self.txtProdLocal.setObjectName("txtProdLocal")
        self.lastUpdateGrid.addWidget(self.txtProdLocal, 2, 1, 1, 1)
        self.txtCustLocal = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtCustLocal.setEnabled(True)
        self.txtCustLocal.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCustLocal.setReadOnly(True)
        self.txtCustLocal.setObjectName("txtCustLocal")
        self.lastUpdateGrid.addWidget(self.txtCustLocal, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lastUpdateGrid.addWidget(self.label_3, 0, 1, 1, 1)
        self.lblCustomer = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblCustomer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblCustomer.setObjectName("lblCustomer")
        self.lastUpdateGrid.addWidget(self.lblCustomer, 1, 0, 1, 1)
        self.lblCatalog = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lblCatalog.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblCatalog.setObjectName("lblCatalog")
        self.lastUpdateGrid.addWidget(self.lblCatalog, 2, 0, 1, 1)
        self.txtCustServer = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.txtCustServer.setEnabled(True)
        self.txtCustServer.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCustServer.setReadOnly(True)
        self.txtCustServer.setObjectName("txtCustServer")
        self.lastUpdateGrid.addWidget(self.txtCustServer, 1, 2, 1, 1)
        self.topGridLayout.addLayout(self.lastUpdateGrid)
        self.verticalLayout.addLayout(self.topGridLayout)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.mainGrid = QtWidgets.QHBoxLayout()
        self.mainGrid.setObjectName("mainGrid")
        self.customerList = QtWidgets.QTreeWidget(self.verticalLayoutWidget)
        self.customerList.setAlternatingRowColors(True)
        self.customerList.setObjectName("customerList")
        self.customerList.headerItem().setText(0, "1")
        self.mainGrid.addWidget(self.customerList)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.mainGrid.addWidget(self.line_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonVisitData = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonVisitData.setObjectName("buttonVisitData")
        self.gridLayout_2.addWidget(self.buttonVisitData, 0, 2, 1, 1)
        self.buttonOrderData = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonOrderData.setObjectName("buttonOrderData")
        self.gridLayout_2.addWidget(self.buttonOrderData, 0, 3, 1, 1)
        self.buttonMasterData = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonMasterData.setObjectName("buttonMasterData")
        self.gridLayout_2.addWidget(self.buttonMasterData, 0, 0, 1, 1)
        self.buttonContactData = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonContactData.setObjectName("buttonContactData")
        self.gridLayout_2.addWidget(self.buttonContactData, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.buttonCreateVisit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonCreateVisit.setObjectName("buttonCreateVisit")
        self.verticalLayout_2.addWidget(self.buttonCreateVisit)
        self.customerInfoStack = QtWidgets.QStackedWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.customerInfoStack.setFont(font)
        self.customerInfoStack.setObjectName("customerInfoStack")
        self.masterPage = QtWidgets.QWidget()
        self.masterPage.setObjectName("masterPage")
        self.layoutWidget = QtWidgets.QWidget(self.masterPage)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 1, 350, 462))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridMasterData = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridMasterData.setContentsMargins(0, 0, 0, 0)
        self.gridMasterData.setObjectName("gridMasterData")
        self.txtFactor = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtFactor.setObjectName("txtFactor")
        self.gridMasterData.addWidget(self.txtFactor, 12, 1, 1, 1)
        self.txtInfoText = QtWidgets.QTextEdit(self.layoutWidget)
        self.txtInfoText.setObjectName("txtInfoText")
        self.gridMasterData.addWidget(self.txtInfoText, 13, 1, 1, 1)
        self.lblAddress1 = QtWidgets.QLabel(self.layoutWidget)
        self.lblAddress1.setObjectName("lblAddress1")
        self.gridMasterData.addWidget(self.lblAddress1, 3, 0, 1, 1)
        self.lblPostOffice = QtWidgets.QLabel(self.layoutWidget)
        self.lblPostOffice.setObjectName("lblPostOffice")
        self.gridMasterData.addWidget(self.lblPostOffice, 6, 0, 1, 1)
        self.txtCityName = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtCityName.setObjectName("txtCityName")
        self.gridMasterData.addWidget(self.txtCityName, 6, 1, 1, 1)
        self.txtPhone2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtPhone2.setObjectName("txtPhone2")
        self.gridMasterData.addWidget(self.txtPhone2, 9, 1, 1, 1)
        self.lblAddress2 = QtWidgets.QLabel(self.layoutWidget)
        self.lblAddress2.setObjectName("lblAddress2")
        self.gridMasterData.addWidget(self.lblAddress2, 4, 0, 1, 1)
        self.lblAccount = QtWidgets.QLabel(self.layoutWidget)
        self.lblAccount.setObjectName("lblAccount")
        self.gridMasterData.addWidget(self.lblAccount, 1, 0, 1, 1)
        self.lblPhone2 = QtWidgets.QLabel(self.layoutWidget)
        self.lblPhone2.setObjectName("lblPhone2")
        self.gridMasterData.addWidget(self.lblPhone2, 9, 0, 1, 1)
        self.txtAccount = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtAccount.setEnabled(True)
        self.txtAccount.setReadOnly(True)
        self.txtAccount.setObjectName("txtAccount")
        self.gridMasterData.addWidget(self.txtAccount, 1, 1, 1, 1)
        self.txtEmail = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtEmail.setObjectName("txtEmail")
        self.gridMasterData.addWidget(self.txtEmail, 11, 1, 1, 1)
        self.lblFactor = QtWidgets.QLabel(self.layoutWidget)
        self.lblFactor.setObjectName("lblFactor")
        self.gridMasterData.addWidget(self.lblFactor, 12, 0, 1, 1)
        self.txtCompany = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtCompany.setObjectName("txtCompany")
        self.gridMasterData.addWidget(self.txtCompany, 2, 1, 1, 1)
        self.txtZipCode = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtZipCode.setObjectName("txtZipCode")
        self.gridMasterData.addWidget(self.txtZipCode, 5, 1, 1, 1)
        self.txtPhone1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtPhone1.setObjectName("txtPhone1")
        self.gridMasterData.addWidget(self.txtPhone1, 8, 1, 1, 1)
        self.lblEmail = QtWidgets.QLabel(self.layoutWidget)
        self.lblEmail.setObjectName("lblEmail")
        self.gridMasterData.addWidget(self.lblEmail, 11, 0, 1, 1)
        self.lblInfoText = QtWidgets.QLabel(self.layoutWidget)
        self.lblInfoText.setWordWrap(True)
        self.lblInfoText.setObjectName("lblInfoText")
        self.gridMasterData.addWidget(self.lblInfoText, 13, 0, 1, 1)
        self.txtAddress2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtAddress2.setObjectName("txtAddress2")
        self.gridMasterData.addWidget(self.txtAddress2, 4, 1, 1, 1)
        self.lblPhone1 = QtWidgets.QLabel(self.layoutWidget)
        self.lblPhone1.setObjectName("lblPhone1")
        self.gridMasterData.addWidget(self.lblPhone1, 8, 0, 1, 1)
        self.lblCompany = QtWidgets.QLabel(self.layoutWidget)
        self.lblCompany.setObjectName("lblCompany")
        self.gridMasterData.addWidget(self.lblCompany, 2, 0, 1, 1)
        self.lblPostCode = QtWidgets.QLabel(self.layoutWidget)
        self.lblPostCode.setObjectName("lblPostCode")
        self.gridMasterData.addWidget(self.lblPostCode, 5, 0, 1, 1)
        self.txtAddress1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtAddress1.setObjectName("txtAddress1")
        self.gridMasterData.addWidget(self.txtAddress1, 3, 1, 1, 1)
        self.buttonArchiveChanges = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonArchiveChanges.setObjectName("buttonArchiveChanges")
        self.gridMasterData.addWidget(self.buttonArchiveChanges, 14, 1, 1, 1)
        self.customerInfoStack.addWidget(self.masterPage)
        self.contactsPage = QtWidgets.QWidget()
        self.contactsPage.setObjectName("contactsPage")
        self.label_6 = QtWidgets.QLabel(self.contactsPage)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 231, 18))
        self.label_6.setObjectName("label_6")
        self.customerInfoStack.addWidget(self.contactsPage)
        self.visitsPage = QtWidgets.QWidget()
        self.visitsPage.setObjectName("visitsPage")
        self.label_5 = QtWidgets.QLabel(self.visitsPage)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 231, 18))
        self.label_5.setObjectName("label_5")
        self.customerInfoStack.addWidget(self.visitsPage)
        self.ordersPage = QtWidgets.QWidget()
        self.ordersPage.setObjectName("ordersPage")
        self.label_2 = QtWidgets.QLabel(self.ordersPage)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 231, 18))
        self.label_2.setObjectName("label_2")
        self.customerInfoStack.addWidget(self.ordersPage)
        self.verticalLayout_2.addWidget(self.customerInfoStack)
        self.mainGrid.addLayout(self.verticalLayout_2)
        self.customerGrid = QtWidgets.QGridLayout()
        self.customerGrid.setObjectName("customerGrid")
        self.mainGrid.addLayout(self.customerGrid)
        self.verticalLayout.addLayout(self.mainGrid)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menuCustomer = QtWidgets.QMenu(self.menuData)
        self.menuCustomer.setObjectName("menuCustomer")
        self.menuServer = QtWidgets.QMenu(self.menuData)
        self.menuServer.setObjectName("menuServer")
        self.menuReports = QtWidgets.QMenu(self.menuData)
        self.menuReports.setObjectName("menuReports")
        self.menuImportEksport = QtWidgets.QMenu(self.menuData)
        self.menuImportEksport.setObjectName("menuImportEksport")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(self.menuHelp)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(True)
        self.toolBar.setIconSize(QtCore.QSize(48, 48))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionHttpGetCustomers = QtWidgets.QAction(MainWindow)
        self.actionHttpGetCustomers.setObjectName("actionHttpGetCustomers")
        self.actionHttpGetCatalog = QtWidgets.QAction(MainWindow)
        self.actionHttpGetCatalog.setObjectName("actionHttpGetCatalog")
        self.actionAboutQt = QtWidgets.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionAboutSoftware = QtWidgets.QAction(MainWindow)
        self.actionAboutSoftware.setObjectName("actionAboutSoftware")
        self.actionCsvFileImport = QtWidgets.QAction(MainWindow)
        self.actionCsvFileImport.setObjectName("actionCsvFileImport")
        self.actionMasterData = QtWidgets.QAction(MainWindow)
        self.actionMasterData.setObjectName("actionMasterData")
        self.actionContactData = QtWidgets.QAction(MainWindow)
        self.actionContactData.setObjectName("actionContactData")
        self.actionVisitData = QtWidgets.QAction(MainWindow)
        self.actionVisitData.setObjectName("actionVisitData")
        self.actionOrderData = QtWidgets.QAction(MainWindow)
        self.actionOrderData.setObjectName("actionOrderData")
        self.actionCreateVisit = QtWidgets.QAction(MainWindow)
        self.actionCreateVisit.setObjectName("actionCreateVisit")
        self.actionCreateCustomer = QtWidgets.QAction(MainWindow)
        self.actionCreateCustomer.setObjectName("actionCreateCustomer")
        self.actionArchiveChanges = QtWidgets.QAction(MainWindow)
        self.actionArchiveChanges.setObjectName("actionArchiveChanges")
        self.actionReport = QtWidgets.QAction(MainWindow)
        self.actionReport.setObjectName("actionReport")
        self.actionZeroDatabase = QtWidgets.QAction(MainWindow)
        self.actionZeroDatabase.setObjectName("actionZeroDatabase")
        self.actionReportList = QtWidgets.QAction(MainWindow)
        self.actionReportList.setObjectName("actionReportList")
        self.menuExit.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionSettings)
        self.menuSettings.addSeparator()
        self.menuCustomer.addAction(self.actionMasterData)
        self.menuCustomer.addAction(self.actionContactData)
        self.menuCustomer.addAction(self.actionVisitData)
        self.menuCustomer.addAction(self.actionOrderData)
        self.menuCustomer.addSeparator()
        self.menuCustomer.addAction(self.actionArchiveChanges)
        self.menuServer.addAction(self.actionHttpGetCatalog)
        self.menuServer.addAction(self.actionHttpGetCustomers)
        self.menuReports.addAction(self.actionReport)
        self.menuReports.addAction(self.actionReportList)
        self.menuImportEksport.addAction(self.actionCsvFileImport)
        self.menuImportEksport.addAction(self.actionZeroDatabase)
        self.menuData.addAction(self.actionCreateCustomer)
        self.menuData.addAction(self.menuCustomer.menuAction())
        self.menuData.addAction(self.menuReports.menuAction())
        self.menuData.addAction(self.menuServer.menuAction())
        self.menuData.addAction(self.menuImportEksport.menuAction())
        self.menuAbout.addAction(self.actionAboutQt)
        self.menuAbout.addAction(self.actionAboutSoftware)
        self.menuHelp.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.customerInfoStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txtNewCompany, self.txtNewPhone1)
        MainWindow.setTabOrder(self.txtNewPhone1, self.buttonCreateCustomer)
        MainWindow.setTabOrder(self.buttonCreateCustomer, self.txtWorkdate)
        MainWindow.setTabOrder(self.txtWorkdate, self.txtCustLocal)
        MainWindow.setTabOrder(self.txtCustLocal, self.txtCustServer)
        MainWindow.setTabOrder(self.txtCustServer, self.txtProdLocal)
        MainWindow.setTabOrder(self.txtProdLocal, self.txtProdServer)
        MainWindow.setTabOrder(self.txtProdServer, self.customerList)
        MainWindow.setTabOrder(self.customerList, self.buttonMasterData)
        MainWindow.setTabOrder(self.buttonMasterData, self.buttonContactData)
        MainWindow.setTabOrder(self.buttonContactData, self.buttonVisitData)
        MainWindow.setTabOrder(self.buttonVisitData, self.buttonOrderData)
        MainWindow.setTabOrder(self.buttonOrderData, self.buttonCreateVisit)
        MainWindow.setTabOrder(self.buttonCreateVisit, self.txtAccount)
        MainWindow.setTabOrder(self.txtAccount, self.txtCompany)
        MainWindow.setTabOrder(self.txtCompany, self.txtAddress1)
        MainWindow.setTabOrder(self.txtAddress1, self.txtAddress2)
        MainWindow.setTabOrder(self.txtAddress2, self.txtZipCode)
        MainWindow.setTabOrder(self.txtZipCode, self.txtCityName)
        MainWindow.setTabOrder(self.txtCityName, self.txtPhone1)
        MainWindow.setTabOrder(self.txtPhone1, self.txtPhone2)
        MainWindow.setTabOrder(self.txtPhone2, self.txtEmail)
        MainWindow.setTabOrder(self.txtEmail, self.txtFactor)
        MainWindow.setTabOrder(self.txtFactor, self.txtInfoText)
        MainWindow.setTabOrder(self.txtInfoText, self.buttonArchiveChanges)

    def retranslateUi(self, MainWindow):
        """

        Args:
            MainWindow:
        """
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Eordre"))
        self.txtNewPhone1.setPlaceholderText(_translate("MainWindow", "Telefon"))
        self.txtNewCompany.setPlaceholderText(_translate("MainWindow", "Firma navn"))
        self.buttonCreateCustomer.setText(_translate("MainWindow", "Opret kunde"))
        self.label.setText(_translate("MainWindow", "Opret nyt besøg/kunde"))
        self.labelWorkdate.setText(_translate("MainWindow", "Arbejdsdato"))
        self.buttonReport.setText(_translate("MainWindow", "Dagsrapport"))
        self.lblAvailable.setText(_translate("MainWindow", "Server dato"))
        self.label_3.setText(_translate("MainWindow", "Synkroniseret"))
        self.lblCustomer.setText(_translate("MainWindow", "Kundeliste"))
        self.lblCatalog.setText(_translate("MainWindow", "Priskatalog"))
        self.buttonVisitData.setText(_translate("MainWindow", "Besøg"))
        self.buttonOrderData.setText(_translate("MainWindow", "Ordrer"))
        self.buttonMasterData.setText(_translate("MainWindow", "Stamdata"))
        self.buttonContactData.setText(_translate("MainWindow", "Kontakter"))
        self.buttonCreateVisit.setText(_translate("MainWindow", "Opret besøg / ordre"))
        self.txtFactor.setPlaceholderText(_translate("MainWindow", "prisliste faktor"))
        self.lblAddress1.setText(_translate("MainWindow", "Adresse"))
        self.lblPostOffice.setText(_translate("MainWindow", "Bynavn"))
        self.txtCityName.setPlaceholderText(_translate("MainWindow", "by navn"))
        self.txtPhone2.setPlaceholderText(_translate("MainWindow", "mobil telefon"))
        self.lblAddress2.setText(_translate("MainWindow", "Adresse"))
        self.lblAccount.setText(_translate("MainWindow", "Konto"))
        self.lblPhone2.setText(_translate("MainWindow", "Tlf2"))
        self.txtEmail.setPlaceholderText(_translate("MainWindow", "epost adresse"))
        self.lblFactor.setText(_translate("MainWindow", "Faktor"))
        self.txtCompany.setPlaceholderText(_translate("MainWindow", "firma navn"))
        self.txtZipCode.setPlaceholderText(_translate("MainWindow", "post nummer"))
        self.txtPhone1.setPlaceholderText(_translate("MainWindow", "primær telefon"))
        self.lblEmail.setText(_translate("MainWindow", "Epost"))
        self.lblInfoText.setText(_translate("MainWindow", "Noter"))
        self.txtAddress2.setPlaceholderText(_translate("MainWindow", "adresse"))
        self.lblPhone1.setText(_translate("MainWindow", "Tlf1"))
        self.lblCompany.setText(_translate("MainWindow", "Firma"))
        self.lblPostCode.setText(_translate("MainWindow", "Postnr"))
        self.txtAddress1.setPlaceholderText(_translate("MainWindow", "adresse"))
        self.buttonArchiveChanges.setText(_translate("MainWindow", "Arkiver rettelser"))
        self.label_6.setText(_translate("MainWindow", "TODO: Vis alle kontakter"))
        self.label_5.setText(_translate("MainWindow", "TODO: Vis alle besøg"))
        self.label_2.setText(_translate("MainWindow", "TODO: Vis tidligere ordrer"))
        self.menuExit.setTitle(_translate("MainWindow", "Afslut"))
        self.menuSettings.setTitle(_translate("MainWindow", "Indstillinger"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.menuCustomer.setTitle(_translate("MainWindow", "Kunde"))
        self.menuServer.setTitle(_translate("MainWindow", "Server"))
        self.menuReports.setTitle(_translate("MainWindow", "Rapporter"))
        self.menuImportEksport.setTitle(_translate("MainWindow", "Import / Eksport"))
        self.menuHelp.setTitle(_translate("MainWindow", "Hjælp"))
        self.menuAbout.setTitle(_translate("MainWindow", "Om"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionExit.setText(_translate("MainWindow", "Afslut"))
        self.actionExit.setIconText(_translate("MainWindow", "Afslut"))
        self.actionExit.setToolTip(_translate("MainWindow", "Afslutter programmet"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Du afslutter programmet ved at trykke her"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSettings.setText(_translate("MainWindow", "Indstillinger"))
        self.actionSettings.setToolTip(_translate("MainWindow", "Tilpas indstillinger"))
        self.actionSettings.setStatusTip(_translate("MainWindow", "Her tilpasser du app\'ens indstillinger"))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionHttpGetCustomers.setText(_translate("MainWindow", "Hent kunder"))
        self.actionHttpGetCustomers.setStatusTip(_translate("MainWindow", "Her hentes kunder fra server"))
        self.actionHttpGetCatalog.setText(_translate("MainWindow", "Hent Prisliste"))
        self.actionHttpGetCatalog.setStatusTip(_translate("MainWindow", "Her hentes prisliste fra server"))
        self.actionAboutQt.setText(_translate("MainWindow", "Om Qt"))
        self.actionAboutQt.setStatusTip(_translate("MainWindow", "Oplysning om Qt version"))
        self.actionAboutSoftware.setText(_translate("MainWindow", "Om programmet"))
        self.actionAboutSoftware.setStatusTip(_translate("MainWindow", "Oplysning om program version"))
        self.actionCsvFileImport.setText(_translate("MainWindow", "Fil import"))
        self.actionMasterData.setText(_translate("MainWindow", "Stamdata"))
        self.actionContactData.setText(_translate("MainWindow", "Kontakter"))
        self.actionVisitData.setText(_translate("MainWindow", "Besøg"))
        self.actionOrderData.setText(_translate("MainWindow", "Ordrer"))
        self.actionCreateVisit.setText(_translate("MainWindow", "Opret ordre"))
        self.actionCreateCustomer.setText(_translate("MainWindow", "Opret kunde"))
        self.actionArchiveChanges.setText(_translate("MainWindow", "Arkiver rettelser"))
        self.actionReport.setText(_translate("MainWindow", "Dagsrapport"))
        self.actionZeroDatabase.setText(_translate("MainWindow", "Nulstil database"))
        self.actionReportList.setText(_translate("MainWindow", "Rapport oversigt"))

