# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visit_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_visitDialog(object):
    def setupUi(self, visitDialog):
        visitDialog.setObjectName("visitDialog")
        visitDialog.resize(636, 568)
        self.formLayoutWidget = QtWidgets.QWidget(visitDialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 321, 252))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formVisit = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formVisit.setContentsMargins(0, 0, 0, 0)
        self.formVisit.setObjectName("formVisit")
        self.txtVisitDate = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtVisitDate.setEnabled(True)
        self.txtVisitDate.setReadOnly(True)
        self.txtVisitDate.setObjectName("txtVisitDate")
        self.formVisit.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtVisitDate)
        self.txtPoBuyer = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtPoBuyer.setObjectName("txtPoBuyer")
        self.formVisit.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtPoBuyer)
        self.txtPoNumber = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtPoNumber.setObjectName("txtPoNumber")
        self.formVisit.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtPoNumber)
        self.txtProductDemo = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtProductDemo.setReadOnly(True)
        self.txtProductDemo.setObjectName("txtProductDemo")
        self.formVisit.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtProductDemo)
        self.txtProductSale = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtProductSale.setReadOnly(True)
        self.txtProductSale.setObjectName("txtProductSale")
        self.formVisit.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtProductSale)
        self.txtInfoText = QtWidgets.QTextEdit(self.formLayoutWidget)
        self.txtInfoText.setObjectName("txtInfoText")
        self.formVisit.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtInfoText)
        self.widgetVisit = QtWidgets.QTableWidget(visitDialog)
        self.widgetVisit.setGeometry(QtCore.QRect(10, 296, 620, 220))
        self.widgetVisit.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.widgetVisit.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.widgetVisit.setObjectName("widgetVisit")
        self.widgetVisit.setColumnCount(10)
        self.widgetVisit.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.widgetVisit.setHorizontalHeaderItem(9, item)
        self.widgetVisit.horizontalHeader().setDefaultSectionSize(70)
        self.widgetVisit.horizontalHeader().setMinimumSectionSize(10)
        self.widgetVisit.verticalHeader().setStretchLastSection(True)
        self.formLayoutWidget_2 = QtWidgets.QWidget(visitDialog)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(339, 40, 291, 206))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formDeliveryAddress = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formDeliveryAddress.setContentsMargins(0, 0, 0, 0)
        self.formDeliveryAddress.setObjectName("formDeliveryAddress")
        self.txtPoCompany = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtPoCompany.setObjectName("txtPoCompany")
        self.formDeliveryAddress.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtPoCompany)
        self.txtPoAddress1 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtPoAddress1.setObjectName("txtPoAddress1")
        self.formDeliveryAddress.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtPoAddress1)
        self.txtPoAddress2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtPoAddress2.setObjectName("txtPoAddress2")
        self.formDeliveryAddress.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtPoAddress2)
        self.txtPoPostcode = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtPoPostcode.setObjectName("txtPoPostcode")
        self.formDeliveryAddress.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtPoPostcode)
        self.txtPoPostoffice = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtPoPostoffice.setObjectName("txtPoPostoffice")
        self.formDeliveryAddress.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtPoPostoffice)
        self.txtPoCountry = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtPoCountry.setObjectName("txtPoCountry")
        self.formDeliveryAddress.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtPoCountry)
        self.gridLayoutWidget = QtWidgets.QWidget(visitDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(340, 260, 290, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridTotals = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridTotals.setContentsMargins(0, 0, 0, 0)
        self.gridTotals.setObjectName("gridTotals")
        self.lblSale = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSale.setObjectName("lblSale")
        self.gridTotals.addWidget(self.lblSale, 1, 0, 1, 1)
        self.lblSas = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSas.setObjectName("lblSas")
        self.gridTotals.addWidget(self.lblSas, 1, 2, 1, 1)
        self.txtVisitSale = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtVisitSale.setEnabled(True)
        self.txtVisitSale.setReadOnly(True)
        self.txtVisitSale.setObjectName("txtVisitSale")
        self.gridTotals.addWidget(self.txtVisitSale, 1, 1, 1, 1)
        self.txtVisitSas = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtVisitSas.setEnabled(True)
        self.txtVisitSas.setReadOnly(True)
        self.txtVisitSas.setObjectName("txtVisitSas")
        self.gridTotals.addWidget(self.txtVisitSas, 1, 3, 1, 1)
        self.lblTotal = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblTotal.setObjectName("lblTotal")
        self.gridTotals.addWidget(self.lblTotal, 1, 4, 1, 1)
        self.txtVisitTotal = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtVisitTotal.setEnabled(True)
        self.txtVisitTotal.setReadOnly(True)
        self.txtVisitTotal.setObjectName("txtVisitTotal")
        self.gridTotals.addWidget(self.txtVisitTotal, 1, 5, 1, 1)
        self.line = QtWidgets.QFrame(visitDialog)
        self.line.setGeometry(QtCore.QRect(330, 40, 16, 250))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(visitDialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 621, 35))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridCustomerVisit = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridCustomerVisit.setContentsMargins(0, 0, 0, 0)
        self.gridCustomerVisit.setObjectName("gridCustomerVisit")
        self.lblCompany = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblCompany.setFont(font)
        self.lblCompany.setObjectName("lblCompany")
        self.gridCustomerVisit.addWidget(self.lblCompany, 0, 0, 1, 1)
        self.txtCompany = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txtCompany.setFont(font)
        self.txtCompany.setReadOnly(True)
        self.txtCompany.setObjectName("txtCompany")
        self.gridCustomerVisit.addWidget(self.txtCompany, 0, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(visitDialog)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 520, 621, 41))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridOrderButtons = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridOrderButtons.setContentsMargins(0, 0, 0, 0)
        self.gridOrderButtons.setObjectName("gridOrderButtons")
        self.btnInsertSale = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btnInsertSale.setDefault(True)
        self.btnInsertSale.setObjectName("btnInsertSale")
        self.gridOrderButtons.addWidget(self.btnInsertSale, 0, 1, 1, 1)
        self.btnArchiveVisit = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btnArchiveVisit.setObjectName("btnArchiveVisit")
        self.gridOrderButtons.addWidget(self.btnArchiveVisit, 0, 2, 1, 1)
        self.btnInsertDemo = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.btnInsertDemo.setObjectName("btnInsertDemo")
        self.gridOrderButtons.addWidget(self.btnInsertDemo, 0, 0, 1, 1)

        self.retranslateUi(visitDialog)
        QtCore.QMetaObject.connectSlotsByName(visitDialog)
        visitDialog.setTabOrder(self.txtVisitDate, self.txtPoBuyer)
        visitDialog.setTabOrder(self.txtPoBuyer, self.txtPoNumber)
        visitDialog.setTabOrder(self.txtPoNumber, self.txtProductDemo)
        visitDialog.setTabOrder(self.txtProductDemo, self.txtProductSale)
        visitDialog.setTabOrder(self.txtProductSale, self.txtInfoText)
        visitDialog.setTabOrder(self.txtInfoText, self.txtPoCompany)
        visitDialog.setTabOrder(self.txtPoCompany, self.txtPoAddress1)
        visitDialog.setTabOrder(self.txtPoAddress1, self.txtPoAddress2)
        visitDialog.setTabOrder(self.txtPoAddress2, self.txtPoPostcode)
        visitDialog.setTabOrder(self.txtPoPostcode, self.txtPoPostoffice)
        visitDialog.setTabOrder(self.txtPoPostoffice, self.txtPoCountry)
        visitDialog.setTabOrder(self.txtPoCountry, self.txtVisitSale)
        visitDialog.setTabOrder(self.txtVisitSale, self.txtVisitSas)
        visitDialog.setTabOrder(self.txtVisitSas, self.txtVisitTotal)
        visitDialog.setTabOrder(self.txtVisitTotal, self.widgetVisit)
        visitDialog.setTabOrder(self.widgetVisit, self.btnInsertSale)

    def retranslateUi(self, visitDialog):
        _translate = QtCore.QCoreApplication.translate
        visitDialog.setWindowTitle(_translate("visitDialog", "Besøg / Indkøbs ordre"))
        self.txtVisitDate.setPlaceholderText(_translate("visitDialog", "Ordre dato"))
        self.txtPoBuyer.setPlaceholderText(_translate("visitDialog", "Indkøber"))
        self.txtPoNumber.setPlaceholderText(_translate("visitDialog", "Rekvisition"))
        self.txtProductDemo.setPlaceholderText(_translate("visitDialog", "Produkt demo"))
        self.txtProductSale.setPlaceholderText(_translate("visitDialog", "Produkt salg"))
        item = self.widgetVisit.horizontalHeaderItem(0)
        item.setText(_translate("visitDialog", "*"))
        item = self.widgetVisit.horizontalHeaderItem(1)
        item.setText(_translate("visitDialog", "Antal"))
        item = self.widgetVisit.horizontalHeaderItem(2)
        item.setText(_translate("visitDialog", "Produkt"))
        item = self.widgetVisit.horizontalHeaderItem(3)
        item.setText(_translate("visitDialog", "Varenr"))
        item = self.widgetVisit.horizontalHeaderItem(4)
        item.setText(_translate("visitDialog", "Tekst"))
        item = self.widgetVisit.horizontalHeaderItem(5)
        item.setText(_translate("visitDialog", "Pris"))
        item = self.widgetVisit.horizontalHeaderItem(6)
        item.setText(_translate("visitDialog", "%"))
        item = self.widgetVisit.horizontalHeaderItem(7)
        item.setText(_translate("visitDialog", "Beløb"))
        item = self.widgetVisit.horizontalHeaderItem(8)
        item.setText(_translate("visitDialog", "SAS"))
        item = self.widgetVisit.horizontalHeaderItem(9)
        item.setText(_translate("visitDialog", "Note"))
        self.txtPoCompany.setPlaceholderText(_translate("visitDialog", "Leveres til"))
        self.txtPoAddress1.setPlaceholderText(_translate("visitDialog", "Leverings adresse 1"))
        self.txtPoAddress2.setPlaceholderText(_translate("visitDialog", "Leverings adresse 2"))
        self.txtPoPostcode.setPlaceholderText(_translate("visitDialog", "Leverings adresse postnummer"))
        self.txtPoPostoffice.setPlaceholderText(_translate("visitDialog", "Leverings adresse bynavn"))
        self.txtPoCountry.setPlaceholderText(_translate("visitDialog", "Leverings adresse land"))
        self.lblSale.setText(_translate("visitDialog", "Salg"))
        self.lblSas.setText(_translate("visitDialog", "SAS"))
        self.lblTotal.setText(_translate("visitDialog", "Total"))
        self.lblCompany.setText(_translate("visitDialog", "Kunde"))
        self.btnInsertSale.setText(_translate("visitDialog", "Indsæt salg"))
        self.btnArchiveVisit.setText(_translate("visitDialog", "Arkiver"))
        self.btnInsertDemo.setText(_translate("visitDialog", "Indsæt demo"))

